import { DEMANDS, GOALS } from './catalog';
import { Questionnaire } from './types';

const agree = { minLabel: 'Discordo', maxLabel: 'Concordo' };
const importance = { minLabel: 'Nada importante', maxLabel: 'Muito importante' };

/**
 * Patient form — section 3 of "HopeMind_Formularios_e_Algoritmo_de_Match".
 * P28–P30 are the mirrored dimensions from section 5 that were missing in section 3.
 */
export const PATIENT_QUESTIONNAIRE: Questionnaire = {
  audience: 'PATIENT',
  version: 'hm-paciente-2026.1',
  sections: [
    {
      id: 'demanda',
      title: 'O que te traz aqui',
      subtitle: 'Isso nos ajuda a encontrar profissionais com experiência no que importa para você.',
      questions: [
        {
          code: 'P01',
          variable: 'demanda',
          type: 'multi',
          prompt: 'Qual o principal motivo da sua busca?',
          help: 'Escolha até 3. Elas serão tratadas como prioridade.',
          required: true,
          usage: 'alta',
          options: DEMANDS,
          maxSelections: 3,
        },
        {
          code: 'P02',
          variable: 'objetivos',
          type: 'multi',
          prompt: 'O que você espera alcançar com a terapia?',
          required: true,
          usage: 'alta',
          options: GOALS,
          exclusive: ['nao_sei'],
        },
        {
          code: 'P19',
          variable: 'temas_experiencia',
          type: 'multi',
          prompt: 'Em quais temas você gostaria que o psicólogo tivesse experiência?',
          required: true,
          usage: 'alta',
          options: DEMANDS,
        },
      ],
    },
    {
      id: 'estilo',
      title: 'Seu jeito na terapia',
      subtitle: 'Não existe resposta certa. Marque o quanto cada frase combina com você.',
      questions: [
        {
          code: 'P03',
          variable: 'preferencia_pratica',
          type: 'scale',
          prompt: 'Quão importante é perceber mudanças práticas no dia a dia?',
          required: true,
          usage: 'media',
          scale: importance,
        },
        {
          code: 'P04',
          variable: 'estilo_reflexao',
          type: 'scale',
          prompt: 'Prefiro que o psicólogo faça muitas perguntas e me ajude a refletir.',
          required: false,
          usage: 'media',
          scale: agree,
        },
        {
          code: 'P05',
          variable: 'estilo_direto',
          type: 'scale',
          prompt: 'Prefiro que o psicólogo seja direto e ofereça orientações práticas.',
          required: false,
          usage: 'alta',
          scale: agree,
        },
        {
          code: 'P06',
          variable: 'estilo_livre',
          type: 'scale',
          prompt: 'Prefiro conversar livremente e deixar a sessão acontecer naturalmente.',
          required: false,
          usage: 'media',
          scale: agree,
        },
        {
          code: 'P07',
          variable: 'preferencia_tarefas',
          type: 'scale',
          prompt: 'Gosto de receber exercícios ou atividades entre as sessões.',
          required: false,
          usage: 'alta',
          scale: agree,
        },
        {
          code: 'P08',
          variable: 'preferencia_passado',
          type: 'scale',
          prompt: 'Prefiro entender profundamente as causas dos problemas.',
          required: false,
          usage: 'media',
          scale: agree,
        },
        {
          code: 'P09',
          variable: 'preferencia_presente',
          type: 'scale',
          prompt: 'Prefiro concentrar o tratamento nos problemas atuais.',
          required: false,
          usage: 'media',
          scale: agree,
        },
      ],
    },
    {
      id: 'conducao',
      title: 'Como você quer ser acompanhado',
      questions: [
        {
          code: 'P10',
          variable: 'autonomia',
          type: 'scale',
          prompt: 'Quero participar das decisões sobre o tratamento.',
          required: true,
          usage: 'alta',
          scale: { minLabel: 'Pouco', maxLabel: 'Muito' },
        },
        {
          code: 'P11',
          variable: 'feedback_preferencia',
          type: 'scale',
          prompt: 'Como você se sente recebendo feedback direto?',
          required: true,
          usage: 'alta',
          scale: { minLabel: 'Prefiro evitar', maxLabel: 'Prefiro que seja direto' },
        },
        {
          code: 'P15',
          variable: 'desafio',
          type: 'scale',
          prompt: 'É importante que o psicólogo questione ou desafie suas ideias quando necessário?',
          required: false,
          usage: 'media',
          scale: importance,
        },
        {
          code: 'P16',
          variable: 'manejo_resistencia',
          type: 'single',
          prompt: 'Quando você evita um assunto, como gostaria que o psicólogo reagisse?',
          required: false,
          usage: 'alta',
          options: [
            { value: 'nao_insistir', label: 'Não insistir' },
            { value: 'perguntar_suavemente', label: 'Perguntar suavemente' },
            { value: 'incentivar', label: 'Me incentivar a falar' },
            { value: 'ser_direto', label: 'Ser direto' },
            { value: 'nao_sei', label: 'Não sei' },
          ],
        },
        {
          code: 'P29',
          variable: 'comunicacao_direta',
          type: 'scale',
          prompt: 'Você prefere um psicólogo com comunicação direta?',
          required: false,
          usage: 'alta',
          scale: agree,
        },
      ],
    },
    {
      id: 'vinculo',
      title: 'A relação com o psicólogo',
      questions: [
        {
          code: 'P12',
          variable: 'relacao_preferencia',
          type: 'single',
          prompt: 'Que relação você espera ter com o psicólogo?',
          required: true,
          usage: 'media',
          options: [
            { value: 'objetiva', label: 'Mais objetiva' },
            { value: 'profissional_acolhedora', label: 'Profissional e acolhedora' },
            { value: 'muito_acolhedora', label: 'Muito acolhedora e próxima' },
            { value: 'sem_preferencia', label: 'Sem preferência' },
          ],
        },
        {
          code: 'P28',
          variable: 'acolhimento',
          type: 'scale',
          prompt: 'Quão importante é para você um atendimento acolhedor?',
          required: false,
          usage: 'alta',
          scale: importance,
        },
        {
          code: 'P30',
          variable: 'objetivos_claros',
          type: 'scale',
          prompt: 'Quão importante é ter objetivos claros na terapia?',
          required: false,
          usage: 'alta',
          scale: importance,
        },
        {
          code: 'P13',
          variable: 'compreensao',
          type: 'scale',
          prompt: 'É importante sentir que o psicólogo compreende sua maneira de pensar?',
          required: false,
          usage: 'alta',
          scale: importance,
        },
        {
          code: 'P14',
          variable: 'conforto',
          type: 'scale',
          prompt: 'É importante sentir-se confortável para falar de assuntos difíceis?',
          required: false,
          usage: 'alta',
          scale: importance,
        },
      ],
    },
    {
      id: 'preferencias',
      title: 'Preferências pessoais',
      subtitle: 'Opcional. Use só se isso fizer diferença para o seu conforto.',
      questions: [
        {
          code: 'P17',
          variable: 'genero_preferencia',
          type: 'single',
          prompt: 'Você tem preferência de gênero do psicólogo?',
          required: false,
          usage: 'media',
          options: [
            { value: 'sem_preferencia', label: 'Sem preferência' },
            { value: 'homem', label: 'Homem' },
            { value: 'mulher', label: 'Mulher' },
            { value: 'outra', label: 'Outra / preferência específica' },
            { value: 'conversar', label: 'Prefiro conversar com o profissional' },
          ],
        },
        {
          code: 'P18',
          variable: 'caracteristicas_preferidas',
          type: 'multi',
          prompt: 'Alguma característica do profissional aumentaria seu conforto?',
          required: false,
          usage: 'baixa',
          options: [
            { value: 'faixa_semelhante', label: 'Faixa etária semelhante à minha' },
            { value: 'mais_experiente', label: 'Mais experiente' },
            { value: 'mais_jovem', label: 'Mais jovem' },
            { value: 'sem_preferencia', label: 'Sem preferência' },
            { value: 'outra', label: 'Outra' },
          ],
          exclusive: ['sem_preferencia'],
        },
      ],
    },
    {
      id: 'logistica',
      title: 'Rotina e formato',
      questions: [
        {
          code: 'P20',
          variable: 'modalidade',
          type: 'single',
          prompt: 'Qual modalidade você prefere?',
          required: true,
          usage: 'filtro',
          options: [
            { value: 'online', label: 'Online' },
            { value: 'presencial', label: 'Presencial' },
            { value: 'tanto_faz', label: 'Tanto faz' },
          ],
        },
        {
          code: 'P20A',
          variable: 'cidade',
          type: 'text',
          prompt: 'Em qual cidade você prefere o atendimento presencial?',
          help: 'Usamos só para encontrar profissionais na sua região.',
          required: true,
          usage: 'filtro',
          maxLength: 80,
          showIf: { code: 'P20', in: ['presencial', 'tanto_faz'] },
        },
        {
          code: 'P21',
          variable: 'frequencia',
          type: 'single',
          prompt: 'Com que frequência você gostaria de ter sessões?',
          required: true,
          usage: 'media',
          options: [
            { value: 'semanal', label: 'Semanal' },
            { value: 'quinzenal', label: 'Quinzenal' },
            { value: 'nao_sei', label: 'Ainda não sei' },
          ],
        },
        {
          code: 'P22',
          variable: 'disponibilidade',
          type: 'schedule',
          prompt: 'Quando você costuma ter disponibilidade?',
          help: 'Toque nos períodos em que você conseguiria fazer uma sessão.',
          required: true,
          usage: 'filtro',
        },
      ],
    },
    {
      id: 'historico',
      title: 'Sua experiência com terapia',
      questions: [
        {
          code: 'P23',
          variable: 'experiencia_terapia',
          type: 'single',
          prompt: 'Você já fez terapia?',
          required: true,
          usage: 'baixa',
          options: [
            { value: 'nunca', label: 'Nunca' },
            { value: 'atualmente', label: 'Faço atualmente' },
            { value: 'anteriormente', label: 'Já fiz anteriormente' },
          ],
        },
        {
          code: 'P24',
          variable: 'experiencia_anterior',
          type: 'scale',
          prompt: 'Como foi sua experiência anterior?',
          required: false,
          usage: 'baixa',
          scale: { minLabel: 'Muito negativa', maxLabel: 'Muito positiva', allowNotApplicable: true },
          showIf: { code: 'P23', notIn: ['nunca'] },
        },
        {
          code: 'P25',
          variable: 'expectativas_texto',
          type: 'text',
          prompt: 'O que você gostaria que fosse diferente desta vez?',
          required: false,
          usage: 'apoio',
          maxLength: 1000,
          showIf: { code: 'P23', notIn: ['nunca'] },
        },
      ],
    },
    {
      id: 'seguranca',
      title: 'Como você está agora',
      subtitle:
        'Estas respostas não entram na recomendação. Elas servem para garantir que você receba apoio adequado, se precisar.',
      questions: [
        {
          code: 'P26',
          variable: 'risco_autoagressao',
          type: 'single',
          prompt: 'Nas últimas semanas, você teve pensamentos de não querer estar vivo ou de se machucar?',
          required: true,
          usage: 'seguranca',
          options: [
            { value: 'nao', label: 'Não' },
            { value: 'sim', label: 'Sim' },
            { value: 'conversar', label: 'Prefiro conversar com um profissional' },
          ],
        },
        {
          code: 'P27',
          variable: 'risco_imediato',
          type: 'single',
          prompt: 'Você acredita estar em perigo imediato neste momento?',
          required: true,
          usage: 'seguranca',
          options: [
            { value: 'nao', label: 'Não' },
            { value: 'sim', label: 'Sim' },
            { value: 'nao_sei', label: 'Não sei' },
          ],
        },
      ],
    },
  ],
};
