import { APPROACHES, DEMANDS, PRACTICE_TIME, PUBLICS } from './catalog';
import { Questionnaire } from './types';

const muchLittle = { minLabel: 'Pouco', maxLabel: 'Muito' };

/**
 * Psychologist form — section 4 of the requirements doc.
 * S19–S21 are the mirrored dimensions from section 5 that were missing in section 4.
 */
export const PSYCHOLOGIST_QUESTIONNAIRE: Questionnaire = {
  audience: 'PSYCHOLOGIST',
  version: 'hm-psicologo-2026.1',
  sections: [
    {
      id: 'pratica',
      title: 'Sua prática clínica',
      questions: [
        {
          code: 'S01',
          variable: 'tempo_pratica',
          type: 'single',
          prompt: 'Há quanto tempo você atua na clínica?',
          required: true,
          usage: 'baixa',
          options: PRACTICE_TIME,
        },
        {
          code: 'S02',
          variable: 'publicos',
          type: 'multi',
          prompt: 'Quais públicos você atende?',
          required: true,
          usage: 'filtro',
          options: PUBLICS,
        },
        {
          code: 'S05',
          variable: 'abordagens',
          type: 'multi',
          prompt: 'Quais abordagens você utiliza?',
          required: true,
          usage: 'informativo',
          options: APPROACHES,
        },
      ],
    },
    {
      id: 'demandas',
      title: 'Demandas que você atende',
      subtitle: 'Declare sua experiência com sinceridade — ela pesa bastante na recomendação.',
      questions: [
        {
          code: 'S03',
          variable: 'demandas_experiencia',
          type: 'multi',
          prompt: 'Em quais demandas você tem experiência clínica?',
          required: true,
          usage: 'alta',
          options: DEMANDS.filter((d) => d.value !== 'outro'),
        },
        {
          code: 'S04',
          variable: 'experiencia_demanda',
          type: 'matrix',
          prompt: 'Qual o seu nível de experiência em cada uma?',
          required: true,
          usage: 'alta',
          rowsFrom: 'S03',
          scale: { minLabel: 'Pouca', maxLabel: 'Alta experiência' },
        },
        {
          code: 'S13',
          variable: 'nao_atende',
          type: 'multi',
          prompt: 'Há demandas que você não atende?',
          help: 'Pacientes com essas demandas como prioridade não serão indicados a você.',
          required: false,
          usage: 'filtro',
          options: DEMANDS.filter((d) => d.value !== 'outro'),
        },
      ],
    },
    {
      id: 'estilo',
      title: 'Seu estilo de condução',
      subtitle: 'Estas respostas são comparadas com as preferências dos pacientes.',
      questions: [
        {
          code: 'S06',
          variable: 'estrutura',
          type: 'scale',
          prompt: 'Quão estruturadas são as suas sessões?',
          required: true,
          usage: 'alta',
          scale: { minLabel: 'Livres', maxLabel: 'Estruturadas' },
        },
        { code: 'S07', variable: 'tarefas', type: 'scale', prompt: 'Você usa tarefas entre as sessões?', required: true, usage: 'alta', scale: muchLittle },
        { code: 'S08', variable: 'feedback', type: 'scale', prompt: 'Quanto você oferece feedback direto?', required: true, usage: 'alta', scale: muchLittle },
        {
          code: 'S09',
          variable: 'direcionamento',
          type: 'scale',
          prompt: 'Quanto você direciona ativamente a sessão?',
          required: true,
          usage: 'alta',
          scale: muchLittle,
        },
        {
          code: 'S10',
          variable: 'passado',
          type: 'scale',
          prompt: 'Quanto você explora acontecimentos passados?',
          required: true,
          usage: 'media',
          scale: muchLittle,
        },
        {
          code: 'S11',
          variable: 'presente',
          type: 'scale',
          prompt: 'Quanto você foca nos problemas atuais?',
          required: true,
          usage: 'media',
          scale: muchLittle,
        },
        {
          code: 'S12',
          variable: 'autonomia',
          type: 'scale',
          prompt: 'Quanto você incentiva o paciente a participar das decisões?',
          required: true,
          usage: 'alta',
          scale: muchLittle,
        },
      ],
    },
    {
      id: 'relacao',
      title: 'Relação terapêutica',
      questions: [
        {
          code: 'S19',
          variable: 'acolhimento',
          type: 'scale',
          prompt: 'Quanto o acolhimento está presente na sua prática?',
          required: true,
          usage: 'alta',
          scale: muchLittle,
        },
        {
          code: 'S20',
          variable: 'comunicacao_direta',
          type: 'scale',
          prompt: 'Quão direta é a sua comunicação?',
          required: true,
          usage: 'alta',
          scale: muchLittle,
        },
        {
          code: 'S21',
          variable: 'objetivos_claros',
          type: 'scale',
          prompt: 'Quanto você trabalha com objetivos claros e combinados?',
          required: true,
          usage: 'alta',
          scale: muchLittle,
        },
        {
          code: 'S17',
          variable: 'perfis_experiencia',
          type: 'multi',
          prompt: 'Com quais perfis de paciente você tem mais experiência?',
          required: false,
          usage: 'media',
          options: [
            { value: 'reservado', label: 'Mais reservado' },
            { value: 'comunicativo', label: 'Comunicativo' },
            { value: 'objetivos', label: 'Orientado a objetivos' },
            { value: 'autoconhecimento', label: 'Busca autoconhecimento' },
            { value: 'orientacao_pratica', label: 'Prefere orientação prática' },
            { value: 'exploracao_emocional', label: 'Prefere exploração emocional' },
            { value: 'outros', label: 'Outros' },
          ],
        },
      ],
    },
    {
      id: 'logistica',
      title: 'Formato e agenda',
      questions: [
        {
          code: 'S14',
          variable: 'modalidade',
          type: 'multi',
          prompt: 'Em quais modalidades você atende?',
          required: true,
          usage: 'filtro',
          options: [
            { value: 'online', label: 'Online' },
            { value: 'presencial', label: 'Presencial' },
          ],
        },
        {
          code: 'S15',
          variable: 'regiao',
          type: 'text',
          prompt: 'Em qual cidade fica o seu consultório?',
          help: 'O endereço completo não é exibido para o paciente.',
          required: true,
          usage: 'filtro',
          maxLength: 80,
          showIf: { code: 'S14', in: ['presencial'] },
        },
        {
          code: 'S16',
          variable: 'disponibilidade',
          type: 'schedule',
          prompt: 'Em quais períodos você tem agenda disponível?',
          required: true,
          usage: 'filtro',
        },
      ],
    },
    {
      id: 'seguranca',
      title: 'Segurança e encaminhamento',
      questions: [
        {
          code: 'S18',
          variable: 'restricoes_clinicas',
          type: 'single',
          prompt: 'Como você lida com pacientes que relatam risco de autoagressão?',
          help: 'O protocolo final deve ser definido com a equipe clínica responsável.',
          required: true,
          usage: 'seguranca',
          options: [
            { value: 'atende_risco', label: 'Atendo, com protocolo de segurança' },
            { value: 'encaminha_risco', label: 'Prefiro encaminhar para outro serviço' },
          ],
        },
      ],
    },
  ],
};
